version: '3.8'
services:
    # API
    api:
        container_name: laranews-api
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: laranews-api
        volumes:
            - ./backend:/var/www/html/backend
            - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./config/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        restart: unless-stopped
        environment:
            SERVICE_NAME: laranews-api
            SERVICE_TAGS: dev
        networks:
            - laravel-news
        depends_on:
            - db
    # DB Service
    db:
        container_name: laranews-db
        image: mysql:8.0.33
        restart: unless-stopped
        tty: true
        ports:
            - '3308:3306'
        environment:
            SERVICE_NAME: mysql
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - laravel-news
    #frontend
    frontend:
        container_name: next_app
        build:
          context: ./frontend/
          dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./frontend:/var/www/html/frontend
        depends_on:
            - api
        networks:
            - laravel-news
    # NGINX
    nginx:
        container_name: laranews-nginx
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - '8082:80'
            - '443:443'
        volumes:
            - ./backend:/var/www/html/backend
            - ./backend:/var/www/html/frontend
            - ./config/nginx:/etc/nginx/conf.d/
        depends_on:
            - frontend
        networks:
            - laravel-news
networks:
    laravel-news:
        driver: bridge
volumes:
    dbdata:
        driver: local

